### ISSUE TITLE
Implement Edge and Lane Behavior

### ISSUE THREAD

**Issue by chrisblatchley** [chrisblatchley/sumo-cuda#2]
TODO: Fill out exactly what we're doing here.

**Comment by thaddeus** [comment]
Added: Basic plan movement functionality
Added: Basic execute movement functionality
Added: Container for vehicle positions within Edges
Removed: Redundant Edge data within Lanes

**Comment by thaddeus** [comment]
Removed vehicle position containers - redundant/unecessary data storage.
Refactored edge and lane functionality.
